### ISSUE TITLE
Zadanie 2, aplikacja nie przechodzi testów

### ISSUE THREAD

**Issue by RafalKornel** [daftcode/daftacademy-python_levelup-spring2019#10]
Aplikacja działa tak, jak powinna, jednak nie chce przejść testów. Oto błędy które zwraca repl:

> Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 22, in test_method_login_success
    self.assertTrue(r1.history[-1].status_code in (301, 302, 303))
IndexError: list index out of range

> Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 34, in test_method_login_unauthorized
    self.assertEqual(response.status_code, 401)
AssertionError: 200 != 401

Przyznam, że pierwszego błędu w ogóle nie rozumiem, a drugi jest dziwny, ponieważ nieudana próba zalogowania zwraca 401.

Link do repo z aplikacją: [https://github.com/RafalKornel/I_dont_like_trains/blob/master/app.py](url)

Link do aplikacji jakby ktoś chciał zobaczyć jak działa: [https://second-app-daft.herokuapp.com/](url)

**Comment by RafalKornel** [comment]
Rozwiązałem: dopiero po prześledzeniu logów zauważyłem że trzeba użyć basic auth.
