### ISSUE TITLE
3.6

### ISSUE THREAD

**Issue by przemko0** [daftcode/daftacademy-python_levelup-spring2019#17]
Witam, moja appka nie chce przejść testów delete w zadaniu 3.6. W logach nie ma w ogóle zmianki o tym, żeby był wykonany jakiś request z tą metodą. Odpowiedź na request DELETE /trains/3?format=json
```json
{
    "who" : "JA",
    "where" : "Wąchock",
    "trucks" : 21,
    "locomotive" : "gama",
    "date" : "2019-01-01"
}
```
Lokalnie zdaje się działać wszystko poprawnie, wydaje mi się, że może to być wina testu. 
Kod odpowiadający za tą ścieżkę:
```python
@app.route('/trains/<int:uuid>', methods=['GET', 'DELETE'])
@app.route('/trains/uuid_<int:uuid>', methods=['GET', 'DELETE'])
@secured('/login')
def specific_train(uuid):
    if request.method == 'GET':
        train_to_pass = None
        for t in app.trains:
            if t.uuid == uuid:
                train_to_pass = t
                break
        if not train_to_pass:
            return "no train with this id", 400
        if request.args.get('format') == 'json':
            return render_template('singleJSON.html', train=train_to_pass)
        else:
            return render_template('singleXML.html', train=train_to_pass)
    if request.method == 'DELETE':
        train_to_pass = None
        for idx in range(len(app.trains)):
            if app.trains[idx].uuid == uuid:
                train_to_pass = app.trains[idx]
                del app.trains[idx]
                break
        if not train_to_pass:
            return 'no train with this id found', 400
        if request.args.get('format') == 'json':
            return render_template('singleJSON.html', train=train_to_pass)
        else:
            return render_template('singleXML.html', train=train_to_pass)
```

**Comment by moty-daft** [comment]
Z tego co widzę, może chodzić o status code. Masz w komunikacie z błędem "200 != 204", czy raczej coś innego?

**Comment by przemko0** [comment]
@moty-daft 
```
Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 40, in test_delete_trains
    self.assertTrue(len(r3.json()) > 0)
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by moty-daft** [comment]
U mnie ten błąd znika, gdy na ścieżce GET /trains (czyli w innej funkcji niż ta, którą wkleiłeś) zwracam JSONa zamiast XMLa. Spróbuj i daj znać.

**Comment by przemko0** [comment]
Pomogło, dzięki
