### ISSUE TITLE
Zadanie 3 - Decode error

### ISSUE THREAD

**Issue by Jareli** [daftcode/daftacademy-python_levelup-spring2019#8]
Cześć,

miałem problem z zaliczeniem testów dla zadania 3 z wykładu 1. Próbowałem różnych rozwiązań, ostatecznie nawet tego zaprezentowanego jako poprawne na wykładzie. Niestety za każdym razem otrzymywałem następujące błędy:
```
Traceback (most recent call last):
  File "/home/runner/unit_tests.py", line 20, in test_show_data_simple_case
    self.assertEqual(json.loads(response.text), data)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Kod mojej aplikacji:
```
# app.py
from flask import Flask, request
app = Flask(__name__)
counter = 1

@app.route('/')
def hello():
    return 'Hello, World!'

@app.route('/request')
def request_info():
    return f'request method: {request.method} url: {request.url} headers: {request.headers}'

@app.route('/method', methods=['GET','POST','PUT','DELETE'])
def request_method():
    return f'{request.method}'

@app.route('/show_data', methods=['POST'])
def show_data():
    return jsonify(request.json)
 
@app.route('/pretty_print_name', methods=['GET','POST'])
def print_name():
    zawartosc = request.get_json()
    imie = zawartosc['name']
    nazwisko = zawartosc['surename']
    return f'Na imię mu {imie}, a nazwisko jego {nazwisko}'

@app.route('/counter')
def licz():
    global counter
    counter += 1
    return str(counter)

if __name__ == '__main__':
    app.run(debug=True)
```

Aplikacja dostępna pod adresem:
https://jarekeliaszapp.herokuapp.com/

**Comment by Jareli** [comment]
Ok. Import jsonify może wydać się naprawdę pomocny w tym przypadku...
Można też zamiast **jsonify** zaimportować json z flask i użyć **json.dumps**. Czy ktoś umiałby wyjaśnić dlaczego problematyczne jest użycie tu metody get_json()?

**Comment by szoz** [comment]
Występuje problem bo ta metoda zwraca niepoprawny JSON - z pojedynczymi cudzysłowami.

**Comment by Jareli** [comment]
Dzięki szoz :)
